language: node_js
node_js:
- lts/*
install:
- npm install
os:
 - windows
script:
- npm run build
deploy:
  provider: pages
  skip-cleanup: true
  keep-history: true
  local-dir: build
  on:
    branch: master
  github-token: $GITHUB_TOKEN
